swagger: '2.0'
info:
  title: DC/OS Pkgpanda API
  version: '1.0.0'
basePath: /pkgpanda


definitions:

  PackageId:
    description: A unique pkgpanda package ID. Composed of a name and a version separated by `--`.
    type: string
    example: 'mesos--abcdef'
    # Pattern adapted from pkgpanda/__init__.py.
    pattern: '/^[a-zA-Z0-9@_+]([a-zA-Z0-9@._+\-]*[a-zA-Z0-9@._+])?--[a-zA-Z0-9@_+:.]+$/'

  PackageIdArray:
    description: An array of unique pkgpanda package IDs.
    type: array
    uniqueItems: true
    items:
      $ref: '#/definitions/PackageId'


parameters:

  PackageId:
    name: package-id
    in: path
    required: true
    # From #/definitions/PackageId.
    description: A unique pkgpanda package ID. Composed of a name and a version separated by `--`.
    type: string
    pattern: '/^[a-zA-Z0-9@_+]([a-zA-Z0-9@._+\-]*[a-zA-Z0-9@._+])?--[a-zA-Z0-9@_+:.]+$/'


paths:

  /:
    get:
      summary: List the packages that are present in the node's pkgpanda repository.
      produces:
        - application/json
      responses:
        '200':
          description: A list of the packages on this node.
          schema:
            '$ref': '#/definitions/PackageIdArray'

  /{package-id}:
    get:
      summary: Get a package in the node's pkgpanda repository.
      parameters:
        - '$ref': '#/parameters/PackageId'
      responses:
        '204':
          description: The package is present in this node's pkgpanda repository.
        '404':
          description: The package is not present in this node's pkgpanda repository.
    post:
      summary: Fetch a package from the bootstrap URL configured at /etc/mesosphere/setup-flags/repository-url on this node.
      parameters:
        - '$ref': '#/parameters/PackageId'
      responses:
        '204':
          description: The package was successfully fetched.
        '500':
          description: The package fetch failed.
    delete:
      summary: Remove a package from the node's pkgpanda repository.
      parameters:
        - '$ref': '#/parameters/PackageId'
      responses:
        '204':
          description: The package was successfully deleted.
        '404':
          description: The package is not present in this node's pkgpanda repository.
        '409':
          description: The package is active, so it can't be removed.

  /active/:
    get:
      summary: List packages that are active on this node.
      produces:
        - application/json
      responses:
        '200':
          description: A list of the active packages on this node.
          schema:
            '$ref': '#/definitions/PackageIdArray'
    put:
      summary: Replace the current list of active packages with the packages in the request body.
      consumes:
        - application/json
      parameters:
        - name: packages
          in: body
          required: true
          schema:
            '$ref': '#/definitions/PackageIdArray'
      responses:
        '204':
          description: The packages in the request body have been activated. (This does not necessarily mean that their services started successfully.)
        '409':
          description: One or more packages in the request body are not present in this node's pkgpanda repository.

  /active/{package-id}:
    get:
      summary: Get a package that is active on this node.
      parameters:
        - '$ref': '#/parameters/PackageId'
      responses:
        '204':
          description: The package is active on this node.
        '404':
          description: The package is not active on this node.
